---
configure_katello_organizations:
  - name: MY_ORG
    state: present
    manifest: "{{ configure_katello_manifest_name }}"
    redhat_repository_url: "https://{{ hostvars[groups['sat-eng'][0]]['ansible_fqdn'] }}/pub"

configure_katello_activation_keys:
  - name: Satellite
    organization: MY_ORG
    environment: Library
    content_view: Default Organization View
    subscriptions:
      - name: Red Hat Satellite, Premium (One Year, Enterprise Program)
      - name: Red Hat Enterprise Linux, Premium (One Year, Enterprise Program)
    auto_attach: False

configure_katello_settings:
  - { name: default_download_policy, value: immediate }
  - { name: content_disconnected, value: yes }

configure_katello_domains:
  - name: "{{ hostvars[groups['sat-spoke'][0]]['ansible_domain'] }}"
    organizations:
      - MY_ORG
    locations:
      - MY_ORG
